# Generated by Django 2.2 on 2020-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_number',
            field=models.IntegerField(default=0, max_length=2000, null=True),
        ),
    ]
