# Generated by Django 2.2 on 2020-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200721_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_card_number_encrypted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cvv_encrypted',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expiry_month',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expiry_year',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
