# Generated by Django 2.2 on 2020-07-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200721_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number_encrypted',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cvv_encrypted',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiry_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
