# Generated by Django 2.2 on 2020-07-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200722_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_number_encrypted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cvv_encrypted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_year',
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, null=True)),
                ('cvv', models.CharField(max_length=18, null=True)),
                ('expiry_month', models.CharField(max_length=3, null=True)),
                ('expiry_year', models.CharField(max_length=4, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Customer')),
            ],
        ),
    ]
