# Generated by Django 2.2 on 2020-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200722_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='names_on_card',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
