# Generated by Django 2.2 on 2020-07-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_creditcard_names_on_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
